### PR TITLE
Winnery experiment should output l2 diffs

### PR DESCRIPTION
**Pull request by dorimedini**
Solves #89

### CODE REVIEW

**Comment by galshachaf** [comment]
why not use get_weight_distances that noam added? @dorimedini

**Comment by dorimedini** [comment]
> why not use get_weight_distances that noam added? @dorimedini

Fixed.
@galshachaf it would be better if you used the review API so the fix requests have context and I can mark them as resolved

**Comment by galshachaf** [comment]
kinda felt this is relevant to the whole PR :)

**Comment by dorimedini** [comment]
> kinda felt this is relevant to the whole PR :)

@galshachaf No problem, I read the comments anyway, just the 'quote reply' option sucks the conversations are out of context.

I, of course, only every have at most one issue in my PRs so it doesn't matter, but if in some unimaginable hypothetical situation there are **two** issues and we argue about them (which we kinda like) it gets messy

**Review by galshachaf — APPROVED** [review]

**Pull request merged**
